"""abrisco/rules_doxygen"""

module(
    name = "rules_doxygen",
    version = "0.0.4",
)

bazel_dep(name = "apple_support", version = "1.23.1")
bazel_dep(name = "bazel_features", version = "1.36.0")
bazel_dep(name = "bazel_skylib", version = "1.8.1")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.4")

bazel_dep(name = "stardoc", version = "0.8.0", dev_dependency = True)

internal_deps = use_extension("//doxygen/private:internal_extensions.bzl", "i")
use_repo(
    internal_deps,
    "doxygen_linux_amd64",
    "doxygen_macos_amd64",
    "doxygen_macos_arm64",
    "doxygen_windows_amd64",
)

register_toolchains(
    "//doxygen/toolchain",
    dev_dependency = True,
)
