name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

env:
  BAZEL_STARTUP_FLAGS: --bazelrc=${{ github.workspace }}/.github/github.bazelrc

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-24.04
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true

      # Build and Test the code
      - name: Test
        run: |
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            bazel ${BAZEL_STARTUP_FLAGS[@]} test ///...
          else
            bazel ${BAZEL_STARTUP_FLAGS[@]} test //...
          fi

      # Explicitly test doxygen_binary
      - name: Generate workspace docs
        run: |
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            bazel ${BAZEL_STARTUP_FLAGS[@]} run ///tests/doxygen_runner
          else
            bazel ${BAZEL_STARTUP_FLAGS[@]} run //tests/doxygen_runner
          fi

  ci-buildifier:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      - name: Download Buildifier
        run: |
          wget "https://github.com/bazelbuild/buildtools/releases/download/v8.2.0/buildifier-linux-amd64" -O buildifier
          chmod +x buildifier
      - name: Buildifier
        run: ./buildifier -lint=warn -mode=check -warnings=all -r ${{ github.workspace }}

  ci-clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: '.'
          extensions: 'h,c,cc,proto'
          clangFormatVersion: 14
